# Uncomment this line to define a global platform for your project
platform :ios, "4.3"

source 'git://github.com/CocoaPods/Specs.git'

pod 'luajit', :path => '../../../cocos2d-x-2.1.5/scripting/lua/luajit/ios'
pod 'assets', :path => 'assets'
pod 'OpenUDID', :head
pod 'Reachability', '~> 3.1.1'

pod 'UMengAnalytics', '~> 2.2.1'
pod 'HXAppPlatformKit', :git => 'git@192.168.0.252:ratazzi/HXAppPlatformKit.git', :tag => 'v2.3.0'
