# Uncomment this line to define a global platform for your project
platform :ios, "5.0"

source 'git://github.com/CocoaPods/Specs.git'

pod 'OpenUDID', :head
pod 'assets', :path => 'assets'
pod 'luajit', :path => '../../../cocos2d-x-2.1.5/scripting/lua/luajit/ios'
pod 'Reachability', '~> 3.1.1'

pod 'SBJson', '~> 3.2'
pod 'UMengAnalytics', '~> 2.2.1'
pod 'PP_SDK_iOS', :git => 'git@192.168.0.252:ratazzi/PP_SDK_iOS.git', :tag => 'v1.4.4'
