# Uncomment this line to define a global platform for your project
platform :ios, "6.0.1"

source 'git://github.com/CocoaPods/Specs.git'

pod 'OpenUDID', :head
pod 'assets', :path => 'assets'
pod 'luajit', :path => '../../../cocos2d-x-2.1.5/scripting/lua/luajit/ios'
pod 'Reachability', '~> 3.1.1'

pod 'UMengAnalytics', '~> 2.2.1'
pod 'KY_SDK', :path => '../KY_SDK'
