# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

source 'git://github.com/CocoaPods/Specs.git'

pod 'OpenUDID', :head
pod 'MBProgressHUD', '~> 0.8'
pod 'Reachability', '~> 3.1.1'
pod 'ChartboostSDK', :path => '../ChartboostSDK'
pod 'assets', :path => 'assets'
pod 'lua', :path => '../../../cocos2d-x-2.1.5/scripting/lua/lua'
pod 'Yunyue', :git => 'git@192.168.0.252:ratazzi/yunyue-framework.git'
pod 'ZCPaySDK', :path => '../ZCPaySDK'
pod 'TalkingDataAppCpa', :path => '../TalkingDataAppCpa'
