# Uncomment this line to define a global platform for your project
platform :ios, "6.0"

source 'git://github.com/CocoaPods/Specs.git'

pod 'OpenUDID', :head
pod 'Reachability', '~> 3.2'
pod 'assets', :path => 'assets'
# pod 'lua', :path => '../../../cocos2d-x-2.1.5/scripting/lua/lua'
pod 'luajit', :path => '../../../cocos2d-x-2.1.5/scripting/lua/luajit/ios'

pod 'AS_SDK', :path => '../AS_SDK'
