# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='config/files.proto',
  package='config',
  serialized_pb='\n\x12\x63onfig/files.proto\x12\x06\x63onfig\"V\n\x08\x46ileItem\x12\x0b\n\x03url\x18\x01 \x02(\t\x12\x0b\n\x03md5\x18\x02 \x02(\t\x12\x0c\n\x04size\x18\x03 \x02(\x05\x12\"\n\x05where\x18\x04 \x02(\x0e\x32\x13.config.FileStorage\"\x91\x01\n\x08\x46ileList\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x14\n\x0cversion_name\x18\x02 \x02(\t\x12\x1f\n\x05\x66iles\x18\x03 \x03(\x0b\x32\x10.config.FileItem\x12\x13\n\x0bpkg_version\x18\x04 \x01(\x05\x12\x10\n\x08platform\x18\x05 \x01(\t\x12\x16\n\x0e\x63onfig_version\x18\x06 \x01(\x05*6\n\x0b\x46ileStorage\x12\x0b\n\x07PACKAGE\x10\x01\x12\x0c\n\x08INTERNAL\x10\x02\x12\x0c\n\x08\x45XTERNAL\x10\x03\x42\x02H\x03')

_FILESTORAGE = descriptor.EnumDescriptor(
  name='FileStorage',
  full_name='config.FileStorage',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='PACKAGE', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INTERNAL', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EXTERNAL', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=266,
  serialized_end=320,
)


PACKAGE = 1
INTERNAL = 2
EXTERNAL = 3



_FILEITEM = descriptor.Descriptor(
  name='FileItem',
  full_name='config.FileItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='url', full_name='config.FileItem.url', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='md5', full_name='config.FileItem.md5', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='size', full_name='config.FileItem.size', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='where', full_name='config.FileItem.where', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=116,
)


_FILELIST = descriptor.Descriptor(
  name='FileList',
  full_name='config.FileList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='config.FileList.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='version_name', full_name='config.FileList.version_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='files', full_name='config.FileList.files', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pkg_version', full_name='config.FileList.pkg_version', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='platform', full_name='config.FileList.platform', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='config_version', full_name='config.FileList.config_version', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=119,
  serialized_end=264,
)

_FILEITEM.fields_by_name['where'].enum_type = _FILESTORAGE
_FILELIST.fields_by_name['files'].message_type = _FILEITEM
DESCRIPTOR.message_types_by_name['FileItem'] = _FILEITEM
DESCRIPTOR.message_types_by_name['FileList'] = _FILELIST

class FileItem(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FILEITEM
  
  # @@protoc_insertion_point(class_scope:config.FileItem)

class FileList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FILELIST
  
  # @@protoc_insertion_point(class_scope:config.FileList)

# @@protoc_insertion_point(module_scope)
