
sources = [ '../../cocos2d-x-2.1.5/cocos2dx/texEncrypt.cpp' ]

SharedLibrary( 'texEncrypt', sources,
         CPPPATH = [ '.' ],
         #CPPDEFINES = [ 'CC_UNDER_LINUX', 'LINUX' ],
         CCFLAGS=['-g3'],
)
